### ISSUE TITLE
Crash: how to fix crashes when i launch it? 

### ISSUE THREAD

**Issue by linxon** [DamirPorobic/kImageAnnotator#43]
Hi! I'm try to compile this from https://github.com/DamirPorobic/ksnip/commit/5664ee0c7ec6d8d69f952c3f853e53d23c603708 (latest continuous build) in my gentoo

output:
```
Unknown platform, using default X11 Image Grabber.
Segmentation fault
```

dmesg:
```
[27165.790902] ksnip[4181]: segfault at 55870000002b ip 00007f85b26c420e sp 00007ffdc457efd0 error 4 in libQt5Widgets.so.5.11.3[7f85b2530000+623000]
```

(gdb) run:
```
Starting program: /usr/bin/ksnip 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffe8589700 (LWP 7884)]
Unknown platform, using default X11 Image Grabber.
[New Thread 0x7fffe6ee1700 (LWP 7900)]
[New Thread 0x7fffe63f9700 (LWP 7902)]

Thread 1 "ksnip" received signal SIGSEGV, Segmentation fault.
0x00007ffff624320e in QWidgetPrivate::setEnabled_helper(bool) () from /usr/lib64/libQt5Widgets.so.5
```

(gdb) thread apply all where:
```
Thread 4 (Thread 0x7fffe63f9700 (LWP 7902)):
#0  0x00007ffff48045f3 in poll () from /lib64/libc.so.6
#1  0x00007ffff1a141d9 in ?? () from /usr/lib64/libglib-2.0.so.0
#2  0x00007ffff1a142ec in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#3  0x00007ffff55a30ff in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#4  0x00007ffff554fc6a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#5  0x00007ffff53b5aea in QThread::exec() () from /usr/lib64/libQt5Core.so.5
#6  0x00007ffff53bf40f in ?? () from /usr/lib64/libQt5Core.so.5
#7  0x00007ffff44f39aa in start_thread () from /lib64/libpthread.so.0
#8  0x00007ffff481015f in clone () from /lib64/libc.so.6

Thread 3 (Thread 0x7fffe6ee1700 (LWP 7900)):
#0  0x00007ffff48045f3 in poll () from /lib64/libc.so.6
#1  0x00007ffff1a141d9 in ?? () from /usr/lib64/libglib-2.0.so.0
#2  0x00007ffff1a142ec in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#3  0x00007ffff55a30ff in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#4  0x00007ffff554fc6a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#5  0x00007ffff53b5aea in QThread::exec() () from /usr/lib64/libQt5Core.so.5
#6  0x00007ffff731ede5 in ?? () from /usr/lib64/libQt5DBus.so.5
#7  0x00007ffff53bf40f in ?? () from /usr/lib64/libQt5Core.so.5
#8  0x00007ffff44f39aa in start_thread () from /lib64/libpthread.so.0
#9  0x00007ffff481015f in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x7fffe8589700 (LWP 7884)):
#0  0x00007ffff48045f3 in poll () from /lib64/libc.so.6
#1  0x00007ffff50fc7f7 in ?? () from /usr/lib64/libxcb.so.1
#2  0x00007ffff50fe42a in xcb_wait_for_event () from /usr/lib64/libxcb.so.1
#3  0x00007fffeb336819 in ?? () from /usr/lib64/libQt5XcbQpa.so.5
#4  0x00007ffff53bf40f in ?? () from /usr/lib64/libQt5Core.so.5
#5  0x00007ffff44f39aa in start_thread () from /lib64/libpthread.so.0
#6  0x00007ffff481015f in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x7ffff7fabbc0 (LWP 7867)):
#0  0x00007ffff624320e in QWidgetPrivate::setEnabled_helper(bool) () from /usr/lib64/libQt5Widgets.so.5
#1  0x00007ffff709ff43 in kImageAnnotator::WidgetConfigurator::updateVisibility() () from /usr/lib64/libkImageAnnotator.so.0.1.0
#2  0x00007ffff709efb9 in kImageAnnotator::AnnotationWidget::initGui() () from /usr/lib64/libkImageAnnotator.so.0.1.0
#3  0x00007ffff709f90d in kImageAnnotator::AnnotationWidget::AnnotationWidget(kImageAnnotator::AnnotationArea*, kImageAnnotator::Config*) () from /usr/lib64/libkImageAnnotator.so.0.1.0
#4  0x00007ffff709e114 in kImageAnnotator::CoreView::CoreView(kImageAnnotator::Config*) () from /usr/lib64/libkImageAnnotator.so.0.1.0
#5  0x00007ffff709d8a4 in kImageAnnotator::KImageAnnotatorPrivate::KImageAnnotatorPrivate(kImageAnnotator::KImageAnnotator*) () from /usr/lib64/libkImageAnnotator.so.0.1.0
#6  0x00007ffff709d9f0 in kImageAnnotator::KImageAnnotator::KImageAnnotator() () from /usr/lib64/libkImageAnnotator.so.0.1.0
#7  0x0000555555589011 in ?? ()
#8  0x0000555555572f4a in ?? ()
#9  0x00007ffff472dae7 in __libc_start_main () from /lib64/libc.so.6
#10 0x000055555557345a in ?? ()
```

depgraph:
```
* dependency graph for x11-misc/ksnip-1.5.0_alpha_p20190225
 `--  x11-misc/ksnip-1.5.0_alpha_p20190225  ~amd64 
   `--  dev-qt/qtcore-5.11.3-r2  (dev-qt/qtcore) amd64 
   `--  dev-qt/qtdbus-5.11.3  (dev-qt/qtdbus) amd64 
   `--  dev-qt/qtnetwork-5.11.3  (dev-qt/qtnetwork) amd64  [ssl]
   `--  dev-qt/qtprintsupport-5.11.3  (dev-qt/qtprintsupport) amd64 
   `--  dev-qt/qtwidgets-5.11.3  (dev-qt/qtwidgets) amd64  [png]
   `--  dev-qt/qtxml-5.11.3  (dev-qt/qtxml) amd64 
   `--  dev-qt/qtx11extras-5.11.3  (dev-qt/qtx11extras) amd64 
   `--  x11-libs/kcolorpicker-0.0.1_p20181123  (x11-libs/kcolorpicker) ~amd64 
   `--  x11-libs/kimageannotator-0.1.0_p20190225  (x11-libs/kimageannotator) ~amd64 
   `--  x11-libs/libxcb-1.13.1  (x11-libs/libxcb) amd64 
   `--  virtual/pkgconfig-1  (virtual/pkgconfig) amd64 
   `--  sys-devel/make-4.2.1-r4  (sys-devel/make) amd64 
   `--  dev-util/cmake-3.9.6  (>=dev-util/cmake-3.9.6) amd64 
   `--  dev-vcs/git-2.19.2  (>=dev-vcs/git-1.8.2.1) amd64  [curl]
```

Thank you!

**Comment by DamirPorobic** [comment]
Looking at the code I do see a potential problem but it's only a guess without running it myself against a gentoo machine. I've add a code change 6794f4f which might fix the issue. Could you please test again the AppImage after the CI finishes building the binary?

**Comment by linxon** [comment]
![ksnip_20190226-004053](https://user-images.githubusercontent.com/8144644/53370618-3d9ebb80-395f-11e9-9cd8-e29fe33d809c.png)

**Comment by DamirPorobic** [comment]
Awesome, thanks for reporting and confirming :)
